### ISSUE TITLE
Video lag & motor command lag shows up on Stretch 3s

### ISSUE THREAD

**Issue by hello-binit** [hello-robot/stretch_web_teleop#17]
Video lag & motor command lag shows up on Stretch 3s at HQ (3012 happens instantly, 3002 happens 5 min in). Both when used remotely over tailscale, and locally. Suspicions:

 - WiFi adapter on the robots
 - Bottleneck with streaming 3 cameras

We don't think this is an interface issue. We suspect it's something external, perhaps the rosbridge_suite.

Other robots that have been tested and confirmed not to exhibit this issue:
 - Vinitha's S2+
 - Vy's S2+

## TODO

 - [ ] @hello-binit to test on S3 (3004) locally
 - [ ] @hello-fazil to test on S3 (3002) locally
 - [ ] Make a list of versions (sw & hw) to collect for each test case. Additionally, collect `ros2 topic hz`, collect ros graph, collect htop, collect tf2 tree.

**Comment by hello-vinitha** [comment]
Solved in https://github.com/hello-robot/stretch_web_teleop/commit/0590bec45c10c647b2d91bd5980415ade1810e6a
